// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RazorPagesSports.Migrations
{
    [DbContext(typeof(RazorPagesSportsContext))]
    partial class RazorPagesSportsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("RazorPagesSports.Models.Sports", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("First_Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_of_Game")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number_of_Player")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uniform_Color")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Sports");
                });
#pragma warning restore 612, 618
        }
    }
}
